default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: Voucherific_development
  adapter: mysql2
  pool: 5
  username: root
  password: brasov
  


development: &development
  <<: *default
  database: Voucherific_development

test: &test
  <<: *default
  database: Voucherific_test

production: &production
  <<: *default
  database: Voucherific_productionm


