default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  #database: <%= ENV['VC_DB_NAME'] %>
  adapter: mysql2
  pool: 5
  username: <%= ENV['VC_DB_USERNAME'] %>
  password: <%= ENV['VC_DB_PASSWORD'] %>
  host: <%= ENV['VC_DB_HOST'] %>
  port: <%= ENV['VC_DB_PORT'] %>

development:
  <<: *default
  database: <%= ENV['DEV_VC_DB_NAME'] %>
  #database: Voucherific_development

test: &test
  <<: *default
  database: <%= ENV['TEST_VC_DB_NAME'] %>
  #database: Voucherific_test

production: &production
  <<: *default
  database: <%= ENV['PROD_VC_DB_NAME'] %>
  #database: Voucherific_production
  #database: <%= ENV['VC_DB_NAME'] %>