default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: Voucherific_development
 
  production:
  <<: *default
  database: Voucherific_production
  password: <%= ENV['BREXIT_DATABASE_PASSWORD'] %>
